In [13]:
from pathlib import Path
import sys

import xarray as xr

sys.path.append("../")
from src.readers.geom_reader import load_geodata

ws, gauges = load_geodata(folder_depth="../")
gauges = [i.stem for i in Path("../data/nc_all_q").glob("*.nc") if i.stem in gauges.index]
gauges[0]

'75257'

In [21]:
with xr.open_dataset("../data/nc_all_q/75257.nc") as ds:
    exmp = ds.to_dataframe()
    exmp["t_mean_e5l"] = (exmp["t_max_e5l"] + exmp["t_min_e5l"]) / 2

dataset = "e5l"
gr4j_data = exmp.loc[
    "2008":"2020",
    [
        "q_mm_day",
        "t_min_e5l",
        "t_mean_e5l",
        "t_max_e5l",
        f"prcp_{dataset}",
    ],
]
gr4j_data

            q_mm_day  t_min_e5l  t_mean_e5l  t_max_e5l  prcp_e5l
date
2008-01-01  0.286095  -6.116365   -4.438327  -2.760289  1.229564
2008-01-02  0.281727 -17.413348  -12.013475  -6.613601  0.118667
2008-01-03  0.276268 -22.217803  -20.160638 -18.103473  0.011734
2008-01-04  0.271900 -22.254049  -20.464331 -18.674614  0.011018
2008-01-05  0.271900 -23.594590  -21.319149 -19.043707  0.039781
...              ...        ...         ...        ...       ...
2020-12-27  0.246784 -13.412012   -8.394263  -3.376515  0.886009
2020-12-28  0.251152 -14.933744  -14.212449 -13.491154  0.096165
2020-12-29  0.251152 -14.745517  -13.243887 -11.742256  0.114991
2020-12-30  0.251152 -11.423461   -8.629437  -5.835414  2.087962
2020-12-31  0.247876  -7.058940   -4.741474  -2.424007  2.909529

[4749 rows x 5 columns]

In [ ]:
gr4j_data = exmp.loc[
    "2008":"2020",
    [
        "q_mm_day",
        f"t_min_{dataset}",
        f"t_mean_{dataset}",
        f"t_max_{dataset}",
        f"prcp_{dataset}",
    ],
]
gr4j_data